### ISSUE TITLE
.chcpignore file doesn't work with Windows

### ISSUE THREAD

**Issue by cleaverpj** [nordnet/cordova-hot-code-push-cli#15]
Hi,

I'm trying to make a bower_components directory that gets ignored in hot code push. 

I created the .chcpignore file in the root of the project with contents
bower_components/*

When running cordova-hcp server the contents of the bower_components directory still makes it to chcp.manifest. After this hcp fails to update the clients.

Tested using Windows 7.

Cheers

Phil

**Comment by raiscui** [comment]
me too,  directory ignore work not good,
it is 'recursive-readdir' use matchBase:true for minimatcher

but , if  no matchBase:true, it become like this:
`**/**.map
**/libs/**
**/workers/**
**/manifest.json
**/deviceUpdate/**
**/chcp.json
**/chcp.manifest
**/package.json
**/node_modules/**`

not view good,but work

**Comment by nikDemyankov** [comment]
Understood, thanks for the feedback. I don't have a Windows machine at the moment, so it will take some time to get one...

**Comment by VinceOPS** [comment]
I have the same problem on Linux.

I needed to add **/ before all my paths in .chcpignore.

The reason is that readdir-recursive is given an absolute path (process.cwd() + 'www') and is given a list of relative paths by .chcpignore.

I think the list of ignored entries should be prefixed with process.cwd(), so readdir-recursive can properly ignore them.

**Comment by nikDemyankov** [comment]
Thanks for the input!

**Comment by nikDemyankov** [comment]
> I think we could also ignore lines beginning with a # so we could "properly" insert comments in our .chcpignore file (just like we do with .gitignore files, to eventually explain why something is ignored)

Comments support is added in v1.1.0.

The issue is not yet fully fixed, so keeping it open.
