### ISSUE TITLE
Cannot deploy to frankfurt aws region

### ISSUE THREAD

**Issue by andreialecu** [nordnet/cordova-hot-code-push-cli#19]
The frankfurt aws region uses v4 signatures, which the `node-s3-client` package used to upload files doesn't support: https://github.com/andrewrk/node-s3-client/issues/69

The other main aws lib, knox, doesn't support v4 signatures either: https://github.com/Automattic/knox/issues/254

It would be best if this project would use aws-sdk directly, which doesn't have this problem.

**Comment by nikDemyankov** [comment]
Thanks for the input. Will look into that.

**Comment by andreialecu** [comment]
I've made a PR for this at https://github.com/nordnet/cordova-hot-code-push-cli/pull/21

**Comment by nikDemyankov** [comment]
Merged PR, closing issue. Thanks.
