### ISSUE TITLE
How does cordova-hot-code-push handle incomplete/pending uploads?

### ISSUE THREAD

**Issue by andreialecu** [nordnet/cordova-hot-code-push-cli#20]
Assume I'm uploading a new version of the app to s3, and assume this takes 1 minute for all the files to go through. 

Within this 1 minute, some users open the app and an update check is triggered. Some files are now updated, and some are not, so the user may have 50% of the new files and 50% of the old files. 

Is this scenario handled in any way? I think all files signatures should be checked on the device after they're downloaded, and if they don't completely match, the update should be rejected. Does this feature exist?

**Comment by nikDemyankov** [comment]
it does the hash checking after the download. if during the update download app detects, that not all files were loaded, or their hashes doesn't match the ones that defined in `chcp.manifest` - update is not performed. So the user is safe.
