### ISSUE TITLE
Error: EISDIR, read

### ISSUE THREAD

**Issue by dts** [nordnet/cordova-hot-code-push-cli#22]
I'm getting this error when I try to run it.

```
 $ cordova-hcp server
Running server
Checking:  /Users/dstaudigel/yt/app/www
local_url http://localhost:31284
Config { name: 'YogiTunes',
  ios_identifier: 'net.mountainmandan.yogi-tunes',
  android_identifier: 'net.mountainmandan.yogi-tunes',
  update: 'resume',
  content_url: 'http://app.yogi-tunes.com/versions/www',
  release: '2015.11.20-09.50.21' }

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EISDIR, read
```

I'm on OSX 10.11, node version `v0.10.38` (though the error also occurs with node 4.2.1).  I tried to add debugging logging, stack traces, etc. but was stymied because I couldn't find the events.js file that was actually throwing the error.

**Comment by dts** [comment]
Of note, it works just fine for a fresh ionic project - there must be some directory in my hierarchy that it is not expecting.  Unfortunately, there are a lot of directories in my project that aren't in a stock one!  Any ideas about where I can hook in to figure out which directory it's bonking on?

**Comment by dts** [comment]
Figured it out - it was a `bower link`ed dependency.  During the hashing process, it incorrectly thinks that a symbolic link will be a file and not a directory.

**Comment by nikDemyankov** [comment]
Hmm, as a work around you could either add this symbol link to the ignore list, or if it's content is required - copy that directory to your project.

As I understand, you would like for the CLI client to detect the symbolic links and add their content to the manifest?

**Comment by dts** [comment]
My workaround was to copy it in, and that works fine (of course it's hacky, but whatever).  Yes, I think the ideal behavior should be that it copies the symlinked directory, flat, into the target bundle and the manifest.  That way, you can use symlinked dependencies with `bower link`.
