### ISSUE TITLE
Add support for symbolic links

### ISSUE THREAD

**Issue by nikDemyankov** [nordnet/cordova-hot-code-push-cli#24]
Feature request from issue https://github.com/nordnet/cordova-hot-code-push-cli/issues/22: add support for symbolic links. CLI client should detect them and generate manifest files properly.

**Comment by tropperstyle** [comment]
Any reason why this was immediately closed? I found this issue via https://github.com/nordnet/cordova-hot-code-push-cli/issues/22

**Comment by nikDemyankov** [comment]
My mistake, probably closed this by accident.
