### ISSUE TITLE
The auto-generated chcp.json excludes other config options 

### ISSUE THREAD

**Issue by tmchng** [nordnet/cordova-hot-code-push-cli#25]
I used `cordova-chcp build` command to auto-generate the chcp.json config and manifest, and I noticed that it would wipe out my other settings like `content_url` and `update`.

Is there a way to preserve other settings and only update `release`?

Thanks!

**Comment by nikDemyankov** [comment]
Did you run `cordova-hcp init`? If you did - in your projects root folder should be a file, called `cordova-hcp.json`. It's content is used when you are running `cordova-hcp build`.

Or you can just manually create `cordova-hcp.json` file and put in it your default configuration, including `content_url`.

**Comment by tmchng** [comment]
Got it, thanks!

I think it'll be clearer if the plugin's README also mentions about `cordova-hcp.json`, just to keep things consistent.

**Comment by nikDemyankov** [comment]
Yes, I agree: need to work on simplifying that stuff and making it cleaner. There is an issue for that, so I would not forget - https://github.com/nordnet/cordova-hot-code-push-cli/issues/14
