### ISSUE TITLE
Add option for prefix when deploying files to S3

### ISSUE THREAD

**Issue by alexbuijs** [nordnet/cordova-hot-code-push-cli#29]
I would like to reuse the same S3 bucket for several apps. The s3-sync-aws package supports an prefix option. Can the init and deploy commands be expanded to include this option?

**Comment by nikDemyankov** [comment]
Cool, will check your PR. Thanks.

**Comment by diegodotta** [comment]
Nice idea @alexbuijs, this is a great for creating test/prod server, I create a grunt command to change the s3bucket/content_url before deploy, I change the "s3bucket" var into cordova-hcp.json  to "mybucket/folder" and works well! :dancer:

**Comment by alexbuijs** [comment]
I did that too. What I also did, and what saved me a couple of times, is to add an app version number in the bucket path. This way you can independently hot deploy different versions of the app. This is especially handy if you don't want to enforce the user to always upgrade to the latest version. But even if you do, this can prevent timing issues with deploying the hot code push update and the availability of the new version of the app in the stores. My content_url looks like this: $app/$env/chcp/$app_version/

**Comment by diegodotta** [comment]
Mmmmm... Interesting approach! I'll think about it.

**Comment by nikDemyankov** [comment]
Released in v1.1.0.
