### ISSUE TITLE
Add an option to gzip js files

### ISSUE THREAD

**Issue by nikDemyankov** [nordnet/cordova-hot-code-push-cli#33]
As suggested in https://github.com/nordnet/cordova-hot-code-push/issues/69 , it would be a nice option for the CLI client to gzip files before uploading them to the server. Especially, JS ones.

**Comment by seme1** [comment]
would be really nice if gzip option was added to the cli to automatically gzip content before uploading to S3

**Comment by seme1** [comment]
The following links may help for adding gzip support to the cli:
https://alyssaq.github.io/2015/deploy_gzip_site_s3/
https://github.com/pgherveou/gulp-awspublish
