### ISSUE TITLE
local nginx instead of the server

### ISSUE THREAD

**Issue by IDrinkMoreWater** [nordnet/cordova-hot-code-push-cli#36]
Can I use nginx instead of the nodejs server and Amazon servers?

**Comment by nikDemyankov** [comment]
You can use any server you like. Local server is just for development purpose, and Amazon servers - it's just a feature, nothing more. You are not restricted to them. 

You just need to deploy the result of the `cordova-hcp build` on your server. And correctly configure `content-url` in `config.xml` of your application. On how to do this - please, read the docs both on plugin and CLI client.

**Comment by IDrinkMoreWater** [comment]
Thank you for your quick reply

**Comment by IDrinkMoreWater** [comment]
Thank you for your quick reply

**Comment by nikDemyankov** [comment]
Happy to help :)
