### ISSUE TITLE
Questions about deploying on S3

### ISSUE THREAD

**Issue by guv3n** [nordnet/cordova-hot-code-push-cli#39]
Correct me if I'm wrong but I understand that the files in the S3 bucket are visible to anyone, do you plan on adding a way to set credentials for the app to get the files ?

Not relevant, but when running `cordova-hcp init`, why do you need the `ios_identifier` and `android_identifier` ?

BTW, you made a great work with cordova-hcp and this CLI !

**Comment by nikDemyankov** [comment]
Thanks. Although, I wasn't the one who developed the CLI client in the beginning. And there was a lot of PR from community, which is great. Just need to get my hands on it.

> Correct me if I'm wrong but I understand that the files in the S3 bucket are visible to anyone, do you plan on adding a way to set credentials for the app to get the files ?

Yes, you are right: at the moment there is no way to set credentials in order for plugin to access secured files. This plugin feature is in [plans](https://github.com/nordnet/cordova-hot-code-push/issues/51). Thanks to @davidovich it was even implemented for iOS. I just need to find time to merge his PR and implement the same stuff for Android. At the moment I've been busy with fixing more critical issues.

> Not relevant, but when running cordova-hcp init, why do you need the ios_identifier and android_identifier?

More details about this you can find in the plugins documentation: [here](https://github.com/nordnet/cordova-hot-code-push#application-config) and [here](https://github.com/nordnet/cordova-hot-code-push#request-application-update-through-the-store). In short: you can use them to redirect user on the App Store/Google Play, so they would update the app. This was originally added in the plugin as the request from one of our developers, but not sure, that it is used in any way and should be in there.
