### ISSUE TITLE
deploy via ftp

### ISSUE THREAD

**Issue by mnewmedia** [nordnet/cordova-hot-code-push-cli#4]
I don't have amazon stuff.. =) It's no problem to deploy it to my server, but doing this via the cli would be very nice. So maybe add some FTP or other options for deploying.

Ups just saw `More deployment targets will be added later`, but an issue is anyway ok, so people can track stuff.

PS: very nice stuff you made..!! Will test it deeply.

**Comment by nikDemyankov** [comment]
Thanks for the feedback! Yes, we absolutely need to extend deployment mechanism. Will post update information here as soon as I'll have any. But you always welcomed to contribute :)

**Comment by mnewmedia** [comment]
sorry, but maybe it's deplyoment related, so i aks it here. I'm getting the error `-4`.
I made an extra easy manifest, to test:
```
[
  {
    "file": "C:\\projekte\\ai\\project\\www\\css\\style.css",
    "hash": "0699289c56ae49c509e03e49fdbd0b1b"
  }
]
```
1. I deployed the app to IOS with following files from you:
````
TestProject/
  www/
    css/styles.css
    chcp.json         // old
    chcp.manifest  // old
  cordova.hcp.json
````

2. I changed style.css
3. I run cordova-hcp build
4. It changed -> `chcp.json & chcp.manifesft`

5. I deployed the update to my server, like that:
````
www/
  css/styles.css // here
chcp.json  // new
chcp.manifest  // new
styles.css // or here, tried both
````
so what am I doing wrong?

**Comment by nikDemyankov** [comment]
This is not a CLI issue, more like a question on a plugin.
First, 
```json
[
  {
    "file": "C:\\projekte\\ai\\project\\www\\css\\style.css",
    "hash": "0699289c56ae49c509e03e49fdbd0b1b"
  }
]
```
is incorrect. `file` should be a path, that is relative to `www` folder. Plugin will append path from the `file` to the `content_url` you specified in `chcp.json` file. 

More details on manifest file can be found [here](https://github.com/nordnet/cordova-hot-code-push#content-manifest).

One more note on deployment: you should deploy only stuff from the `www` folder, but `www` folder itself should not be there. For example, let say you have a server on `http://somecoolserver.com`, your cordova project has structure:
```
TestProject/
  config.xml
  hooks/
  node_modules/
  platforms/
  plugins/
  www/
    chcp.manifest
    index.html
    css/
      styles.css
```
You should deploy your `www` folder content so it would be accessible like that:
```
http://somecoolserver.com/index.html
http://somecoolserver.com/css/style.css
http://somecoolserver.com/chcp.manifest
```

**Comment by nikDemyankov** [comment]
On the other hand, if `cordova-hcp build` generated file path as you showed (`C:\\projekte\\ai\\project\\www\\css\\style.css`) - then yes, it is a bug of CLI client on Windows machine. We will investigate that.

**Comment by mnewmedia** [comment]
Yes not really an issue.. 
But why does then the build command generate:
'"file": C:\\projekte\\ai\\project\\www\\css\\style.css"' instead of
'"file": "style.css"'

Ok you got it.. Started to write this a while ago
Writing this comment from mobile device is hard.. 

I will create a full ionic example in order to help others and to try recreate the bug that it reloads the app but, doesnt show the updated css changes..

But anyway thanks alot and cool that your helping me ;)

Maybe i also can help on some other stuff.. But I dont have the time now, to learn c-objective.

**Comment by nikDemyankov** [comment]
No, thank you for the feedback! It is really cool to know that people testing our plugin.

CLI client is fully JavaScript, so you don't have to learn any mobile-native languages, if you want to contribute :) Contribution is not only coding something, but also testing and providing ideas on how to improve. So yeah, you already do that :)

Created new issue regarding windows and build command: https://github.com/nordnet/cordova-hot-code-push-cli/issues/5 . All further discussion should be continued in there.
