### ISSUE TITLE
.chcpignore nested files

### ISSUE THREAD

**Issue by dwhitmore** [nordnet/cordova-hot-code-push-cli#40]
I'm trying to exclude files nested under subdirectories like 'www/src/any/*.*'.

I've tried:
src/**/*
src/**/*.*
src/*
and so on.

I can exclude individual files though.  Also on Windows if that matters.

**Comment by dwhitmore** [comment]
Just noticed this is a copy of #15 .

**Comment by nikDemyankov** [comment]
Yes, you can find a solution for it in that issue.
