### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by mvanhelmont** [nordnet/cordova-hot-code-push-cli#41]
Is there a way to protect the server side? When you now browse to the content_url you can view directly the application!

**Comment by nikDemyankov** [comment]
At the moment CLI client and plugin doesn't support secured server side. There is already a request for that feature, but It's not implemented. To be honest, If someone would want to get access to your code - he can easily get it by decompiling your application: `www` folder is packed with the app, so it's not a big problem.

**Comment by mvanhelmont** [comment]
Yes i understand it's not total secure, but thanks we will see maybe we can fix it on the server side to load a different index file when viewing the url directly.. More so that people don't get a strange behavior.

**Comment by nikDemyankov** [comment]
New version of CHCP plugin now supports custom headers for all requests. For example, you can add auth headers for update download.
