### ISSUE TITLE
getting 403 when deploying 

### ISSUE THREAD

**Issue by frivera77** [nordnet/cordova-hot-code-push-cli#43]
Deploy started
unable to sync: [Error: Bad status code: 403]
unable to sync: [Error: Bad status code: 403]

Cordova CLI 5.0

double checked my Access Key Id and Secret Access Key, same with the cordova-hcp.json file, even the link https://s3.amazonaws.com is showing the content of the bucket.

any idea on this?

**Comment by nikDemyankov** [comment]
Unfortunately I don't have access to aws servers right now, so can't check this feature :(

But according to Amazon documentation this is either "Access Denied" or "There is a problem with your AWS account that prevents the operation from completing successfully". Have you tried to upload files by using some other tool? Like https://aws.amazon.com/sdk-for-node-js/ .

**Comment by frivera77** [comment]
Hi nikDemyankov, thanks for your reply! I resovoled the issue... my bucket security policy was empty and thas was the reason for the 403. BTW Your plugin rocks!

**Comment by nikDemyankov** [comment]
Great :) Thanks.
