### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ryanlin1986** [nordnet/cordova-hot-code-push-cli#52]
C:\Users\ryanl>npm install -g cordova-hot-code-push-cli
npm WARN peerDependencies The peer dependency level@~1.3.0 included from s3-sync-aws will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
|

> ngrok@2.1.8 postinstall C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/a/54cQjE1obr2/ngrok-2.1.1-windows-386.zip ...
ngrok - binary downloaded...
ngrok - binary unpacked.

> leveldown@1.4.6 install C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown
> prebuild --install

prebuild WARN install EPERM, access 'C:\Users\ryanl\AppData\Roaming\npm-cache'
prebuild ERR! configure error
prebuild ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! stack     at failNoPython (C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! stack     at C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:356:11
prebuild ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
prebuild ERR! not ok
prebuild ERR! build Error: Can't find Python executable "python", you can set the PYTHON env variable.
prebuild ERR! build     at failNoPython (C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:401:14)
prebuild ERR! build     at C:\Users\ryanl\AppData\Roaming\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown\node_modules\prebuild\node_modules\node-gyp\lib\configure.js:356:11
prebuild ERR! build     at FSReqWrap.oncomplete (fs.js:95:15)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova-hot-code-push-cli"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ryanl\npm-debug.log

**Comment by nikDemyankov** [comment]
The problem is with installing node modules on Windows machine (some of them). To fix that you need:
1. Have node version 3+. 
2. Install Python 2.7. If I understood correctly - you need exactly that version.
3. Set environment variable for the python. For example: `set PYTHON=C:\Python\bin\Python.exe`

**Comment by ryanlin1986** [comment]
Thanks, works for me
