### ISSUE TITLE
Allow absolute URL for www_directory 

### ISSUE THREAD

**Issue by jbwdevries** [nordnet/cordova-hot-code-push-cli#59]
Our build directory is outside the repo, and at the moment I have add a lot of ../ to make it work.

Not sure how you'd like to support that, but I think code to change is context.js:44:

```
return path.join(process.cwd(), consoleArgs[1]);
```

**Comment by nikDemyankov** [comment]
I'll try to think of something. Shouldn't be too hard. Thanks for the idea.
