### ISSUE TITLE
`cordova-hcp build` should take a directory

### ISSUE THREAD

**Issue by ptarjan** [nordnet/cordova-hot-code-push-cli#6]
During my production deployment, my directory isn't named `www`. I'd rather be able to run 

```
cordova-hcp build my_www_dir
```

or whatever argument you want

**Comment by nikDemyankov** [comment]
Agree, this should be added. Thanks for the feedback!

**Comment by nikDemyankov** [comment]
Now you can define which folder to build: `cordova-hcp build my_www_folder`. By default, `www` is used.
