### ISSUE TITLE
issue in SWIFT_VERSION 

### ISSUE THREAD

**Issue by jvallarvisp** [nordnet/cordova-hot-code-push-cli#61]
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by nikDemyankov** [comment]
How this is related to CLI client? Maybe you missed the repo and wanted to post this message in https://github.com/nordnet/cordova-hot-code-push-local-dev-addon ?
