### ISSUE TITLE
install cordova-hot-code-push-cli bring error

### ISSUE THREAD

**Issue by snwcwwxf** [nordnet/cordova-hot-code-push-cli#62]
platform info:
Node version: v4.5.0
Cordova version: 6.3.1
## Available Android targets:

id: 1 or "android-23"
     Name: Android 6.0
     Type: Platform
     API level: 23
     Revision: 3

error info:
npm WARN peerDependencies The peer dependency level@~1.4.0 included from s3-sync-aws will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated queue-async@1.0.7: renamed to d3-queue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
\

> ngrok@2.2.3 postinstall C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\ngrok
> node ./postinstall.js

ngrok - downloading binary https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-386.zip ...
ngrok - binary downloaded...
ngrok - binary unpacked.

> leveldown@1.4.6 install C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown
> prebuild --install

prebuild WARN install The process cannot access the file because it is being used by another process.
prebuild WARN install \?\C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\level\node_modules\leveldown\build\Release\le
veldown.node
prebuild ERR! clean error
prebuild ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\leve
l\node_modules\leveldown\build\Release\leveldown.node'
prebuild ERR! stack     at Error (native)
prebuild ERR! not ok
prebuild ERR! build Error: EPERM: operation not permitted, unlink 'C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\leve
l\node_modules\leveldown\build\Release\leveldown.node'
prebuild ERR! build     at Error (native)
npm ERR! Windows_NT 5.1.2600
npm ERR! argv "D:\nodejs\node.exe" "D:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "cordova-hot-code-push-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.4.6 install script 'prebuild --install'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\test\cordova\npm-debug.log

**Comment by nikDemyankov** [comment]
> operation not permitted, unlink 'C:\Documents and Settings\Administrator.MICROSOF-7AB4F0\Application Data\npm\node_modules\cordova-hot-code-push-cli\node_modules\leve
> l\node_modules\leveldown\build\Release\leveldown.node'

Maybe npm/node doesn't have enough rights? Also, try to disable you anti-virus. 

You can try to use different suggestions from [this thread](https://github.com/Medium/phantomjs/issues/19).

**Comment by snwcwwxf** [comment]
thanks

**Comment by wmtnl2004git** [comment]
How to solve this problem, my question is the same.

**Comment by nikDemyankov** [comment]
@wmtnl2004git depends on what issue you are having. Can you share a console output? But if it's Windows and npm errors - probably something wrong with the node/npm installation, or permissions... Have you tried suggestions from the post above?

**Comment by west3316** [comment]
uninstall and install, works for me

**Comment by Farmertjes** [comment]
This worked for me in OS X:
1. install yarn
`brew install yarn`
2. install cordova-hcp-cli in node modules folder
`sudo yarn global add cordova-hot-code-push-cli --modules-folder /usr/lib/node_modules`

Thanks to [this comment](https://github.com/inconshreveable/ngrok/issues/429#issuecomment-353593315)
