### ISSUE TITLE
Add optional logging for server (requests for assets as clients fetch updates)

### ISSUE THREAD

**Issue by sgilroy** [nordnet/cordova-hot-code-push-cli#64]
Logging is currently used to indicate when clients connect/disconnect (via socket.io). This only works for clients using [the addon](https://github.com/nordnet/cordova-hot-code-push-local-dev-addon). It would be helpful to also see when clients fetch updates, including clients not using the addon. Without this logging it is hard to figure out if the remote updates are working, especially if the client is slow or has limited bandwidth.

Ideally, `cordova-hcp server` would log more details about addon clients. The following events should get logged:
 - connect and disconnect (already implemented)
 - fetch start
 - fetch complete
 - fetch error
 - update

For each event, include some details about the client:
 - device id (uniquely identify the client)
 - platform (iOS or Android)
 - model (such as iPhone 7)
 - current web version

For clients not connected via socket.io (not using the addon), requests for individual resources could still be logged, and perhaps some details about the client (platform and model) can be inferred from the user agent header of the request.

**Comment by nikDemyankov** [comment]
Yes, that can be helpful during the development. Thanks for the idea.
