### ISSUE TITLE
Unable to know if the update has gone well or not

### ISSUE THREAD

**Issue by lansanasylla** [nordnet/cordova-hot-code-push-cli#68]
I'm trying to use this plugin in my app, that will update our android apps if there is new feature, i would like to know if there is a way to know if yes or not the update gone well then
IF YES : no problem
IF NOT : send an alert or something like that

Can someone help please ?
thanks

**Comment by nikDemyankov** [comment]
My guess, that you are talking about [main plugin](https://github.com/nordnet/cordova-hot-code-push), not this CLI client.

Depending on the way how you are performing updates - you can either [subscribe on the events](https://github.com/nordnet/cordova-hot-code-push/wiki/Listen-for-update-events), or just use [JS API](https://github.com/nordnet/cordova-hot-code-push/wiki/Fetch-update) to fetch and install updates manually. In this case you will have full control on the update results.
