### ISSUE TITLE
Node version > 5.1.0

### ISSUE THREAD

**Issue by pinturic** [nordnet/cordova-hot-code-push-cli#75]
When using a node version greater than 5.1.0 I (obviously) get an error in installing this package since the needed engine is:

```
"engines": {
    "node": ">=0.10.3 <=5.1.0"
  },
```

Is there any reason for that?
Is there any known incompatibility with versions greater than this?

**Comment by iNoles** [comment]
In https://github.com/nordnet/cordova-hot-code-push-cli/blob/dev/v1.2.0/package.json, 
```
"engines": {
    "node": ">=4.2.2"
  },
```

**Comment by zk922** [comment]
I got an error when running ‘cordova-hcp server’ with node version 10.
But it performs nicely at node version 8.11.3.
