### ISSUE TITLE
Hidden files are not deployed in local development mode

### ISSUE THREAD

**Issue by nikDemyankov** [nordnet/cordova-hot-code-push-cli#8]
Relates to https://github.com/nordnet/cordova-hot-code-push/issues/4 issue.

In short: `deploy` command ignores hidden files, while `build` doesn't. `deploy` should not ignore them.

How to reproduce:

1. Create Ionic project and add chcp plugin:

  ```
  ionic start Test blank
  cd ./Test
  ionic build
  ionic plugin add cordova-hot-code-push-plugin
  ```

2. Run server:

  ```sh
  cordova-hcp server
  ```

3. Add `ionicons `:

  ```sh
  ionic add ionicons
  ```

As a result, CLI client will update `chcp.manifest` and add `lib/angular/.bower.json` to it. But if we will try to access it from the browser - it's not gonna be found. This breaks the update procedure.

**Comment by ptarjan** [comment]
This was also the cause of https://github.com/nordnet/cordova-hot-code-push/issues/19 where my `.swp` files weren't being served but were in the manifest

**Comment by nikDemyankov** [comment]
If file is hidden - it is ignored by the CLI client. Hidden files are not gonna break the update logic anymore, unless you intentionally put them in the manifest file. In that case - be sure to make them accessible through the url. Otherwise, you will end up having the same problem. Local dev server doesn't  make them visible.
